apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  name: karan-ingress-ws
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: tenant-details-svc
          servicePort: 3000
        path: /karan(/|$)(.*)
