apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: workshop-deploy
  name: workshop-deploy
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    tier: web
  type: NodePort
status:
  loadBalancer: {}
