apiVersion: v1
kind: Service
metadata:
  labels:
    tier: web
  name: workshop-deploy
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 30879
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: workshop-deploy
  sessionAffinity: None
  type: NodePort
